#!/usr/bin/env python3
"""Upload contrastive pairs to a private Hugging Face dataset.

Usage:
    python src/huggingface/upload_pairs.py <repo_id> [--pairs-dir output/pairs]

Example:
    python src/huggingface/upload_pairs.py myorg/contrastive-pairs
    python src/huggingface/upload_pairs.py myorg/contrastive-pairs --pairs-dir output/pairs
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from datasets import Dataset

from data.contrastive_dataset import ContrastiveDataset


def _build_dataset_card(repo_id: str, cd: ContrastiveDataset) -> str:
    """Generate a dataset card (README.md) from the loaded pairs."""
    pairs = cd.pairs
    scenarios = sorted({p.scenario_name for p in pairs})
    contrast_types = sorted({p.contrast_type for p in pairs})
    tools = sorted({p.anchor_tool for p in pairs} | {p.contrast_tool for p in pairs})

    scenario_counts = Counter(p.scenario_name for p in pairs)
    ct_counts = Counter(p.contrast_type for p in pairs)

    scenario_table = "\n".join(
        f"| {name} | {count:,} |" for name, count in sorted(scenario_counts.items())
    )
    ct_table = "\n".join(f"| {name} | {count:,} |" for name, count in sorted(ct_counts.items()))

    return f"""---
license: apache-2.0
task_categories:
  - text-classification
tags:
  - contrastive
  - sae
  - sparse-autoencoder
  - tool-selection
size_categories:
  - {_size_category(len(pairs))}
---

# {repo_id.split("/")[-1]}

Contrastive pairs dataset for training Sparse Autoencoders (SAEs) to identify decision-relevant features in language model activations.

## Overview

- **Total pairs**: {len(pairs):,}
- **Scenarios**: {len(scenarios)}
- **Contrast types**: {len(contrast_types)}
- **Tools**: {len(tools)}

## Schema

| Column | Type | Description |
|--------|------|-------------|
| `pair_id` | string | Unique pair identifier |
| `anchor_prompt` | string | First user request |
| `anchor_tool` | string | Optimal tool for anchor |
| `contrast_prompt` | string | Second user request (similar but different tool) |
| `contrast_tool` | string | Optimal tool for contrast |
| `shared_intent` | string | What makes both requests similar |
| `semantic_similarity` | float | 0-1 similarity score |
| `contrast_type` | string | Type of contrast (e.g. internal_vs_external) |
| `distinguishing_signal` | string | Key difference driving tool choice |
| `scenario_name` | string | Scenario that generated this pair |

## Pairs per scenario

| Scenario | Count |
|----------|-------|
{scenario_table}

## Pairs per contrast type

| Contrast type | Count |
|---------------|-------|
{ct_table}

## Tools

{", ".join(f"`{t}`" for t in tools)}

## Usage

```python
from datasets import load_dataset

ds = load_dataset("{repo_id}", split="train")
```

Generated by [kiji-inspector](https://github.com/dataiku/kiji-inspector).
"""


def _size_category(n: int) -> str:
    if n < 1_000:
        return "n<1K"
    elif n < 10_000:
        return "1K<n<10K"
    elif n < 100_000:
        return "10K<n<100K"
    elif n < 1_000_000:
        return "100K<n<1M"
    else:
        return "1M<n<10M"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Upload contrastive pairs to a private Hugging Face dataset.",
    )
    p.add_argument(
        "repo_id",
        type=str,
        help="Hugging Face dataset repo ID (e.g. myorg/contrastive-pairs).",
    )
    p.add_argument(
        "--pairs-dir",
        type=str,
        default="output/pairs",
        help="Path to pairs parquet directory (default: output/pairs).",
    )
    p.add_argument(
        "--revision",
        type=str,
        default=None,
        help="Branch/revision to push to (default: main).",
    )
    p.add_argument(
        "--commit-message",
        type=str,
        default="Upload contrastive pairs",
        help="Commit message for the push.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    pairs_path = Path(args.pairs_dir)
    if not pairs_path.exists() or not list(pairs_path.glob("shard_*.parquet")):
        print(f"ERROR: no pair parquet shards found in {pairs_path}")
        sys.exit(1)

    print(f"Loading pairs from {pairs_path}...")
    cd = ContrastiveDataset.from_parquet(args.pairs_dir)
    print(f"  Loaded {len(cd.pairs)} pairs")

    records = [
        {
            "pair_id": p.pair_id,
            "anchor_prompt": p.anchor_prompt,
            "anchor_tool": p.anchor_tool,
            "contrast_prompt": p.contrast_prompt,
            "contrast_tool": p.contrast_tool,
            "shared_intent": p.shared_intent,
            "semantic_similarity": p.semantic_similarity,
            "contrast_type": p.contrast_type,
            "distinguishing_signal": p.distinguishing_signal,
            "scenario_name": p.scenario_name,
        }
        for p in cd.pairs
    ]

    ds = Dataset.from_list(records)
    print(f"  Dataset: {ds}")

    print("\nGenerating dataset card...")
    card = _build_dataset_card(args.repo_id, cd)

    print(f"Pushing to https://huggingface.co/datasets/{args.repo_id} (private)...")
    ds.push_to_hub(
        args.repo_id,
        private=True,
        revision=args.revision,
        commit_message=args.commit_message,
    )

    from huggingface_hub import HfApi

    api = HfApi()
    api.upload_file(
        path_or_fileobj=card.encode(),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="dataset",
        revision=args.revision,
        commit_message="Update dataset card",
    )
    print("Done.")


if __name__ == "__main__":
    main()
