#!/usr/bin/env python3
"""Upload trained SAE checkpoints for all layers to a single Hugging Face repo.

Discovers layer_* directories under the output root and uploads each layer's
activations/ and sae_checkpoints/ subdirectories, preserving the directory
structure in the repo.  Also uploads the pairs/ directory if present.

Usage:
    python -m huggingface.upload_sae <repo_id> [--output-dir /ephemeral/output]

Example:
    python -m huggingface.upload_sae myorg/kiji-inspector-model
    python -m huggingface.upload_sae myorg/kiji-inspector-model --output-dir /ephemeral/output
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch
from huggingface_hub import HfApi


def _build_model_card(
    repo_id: str,
    layers: list[str],
    layer_summaries: dict[str, dict],
) -> str:
    """Generate a model card (README.md) summarising all uploaded layers."""

    layers_table_rows = []
    arch_section = ""

    for layer_name in sorted(layers, key=lambda name: int(name.split("_")[1])):
        info = layer_summaries.get(layer_name, {})
        n_features = info.get("n_features", "?")
        n_contrasts = info.get("n_contrasts", "?")
        layers_table_rows.append(f"| `{layer_name}` | {n_features} | {n_contrasts} |")

        # Use the first layer with a checkpoint for the architecture section
        if not arch_section and info.get("config"):
            config = info["config"]
            d_model = config.get("d_model", "unknown")
            d_sae = config.get("d_sae", "unknown")
            dtype = config.get("dtype", "unknown")
            bandwidth = config.get("bandwidth", "unknown")
            num_params_str = info.get("num_params_str", "unknown")
            config_table = "\n".join(f"| `{k}` | `{v}` |" for k, v in sorted(config.items()))
            arch_section = f"""
## Architecture

```
input x (d_model={d_model})
    |
    +-> W_enc @ (x - b_dec) + b_enc -> JumpReLU(-, theta) -> features (d_sae={d_sae})
    |
    +-> W_dec @ features + b_dec -> reconstruction (d_model={d_model})
```

- **Type**: JumpReLU SAE with learnable per-feature thresholds
- **Parameters**: {num_params_str}
- **dtype**: {dtype}
- **d_model**: {d_model}
- **d_sae**: {d_sae}
- **bandwidth**: {bandwidth}

## Config

| Key | Value |
|-----|-------|
{config_table}
"""

    layers_table = "\n".join(layers_table_rows)

    return f"""---
license: apache-2.0
tags:
  - sparse-autoencoder
  - sae
  - mechanistic-interpretability
  - tool-selection
---

# {repo_id.split("/")[-1]}

JumpReLU Sparse Autoencoders (SAEs) trained on contrastive activation data for mechanistic interpretability of tool-selection decisions.

## Layers

| Layer | Described features | Contrast types |
|-------|--------------------|----------------|
{layers_table}
{arch_section}
## Repo structure

```
├── layer_<N>/
│   ├── activations/
│   │   ├── contrastive_features.json
│   │   ├── feature_descriptions.json
│   │   ├── shard_*.npy
│   │   └── ...
│   └── sae_checkpoints/
│       ├── sae_final.pt
│       ├── config.json
│       └── ...
└── pairs/
    ├── scenarios_meta.json
    └── shard_*.parquet
```

## Usage

```python
from sae.model import JumpReLUSAE

sae = JumpReLUSAE.from_pretrained("layer_17/sae_checkpoints/sae_final.pt", device="cuda")
features = sae.encode(activations)
reconstruction = sae.decode(features)
```

Generated by [kiji-inspector](https://github.com/dataiku/kiji-inspector).
"""


def _summarise_layer(layer_dir: Path) -> dict:
    """Extract summary info for a single layer directory."""
    info: dict = {}

    desc_path = layer_dir / "activations" / "feature_descriptions.json"
    if desc_path.is_file():
        with open(desc_path) as f:
            info["n_features"] = len(json.load(f))

    cf_path = layer_dir / "activations" / "contrastive_features.json"
    if cf_path.is_file():
        with open(cf_path) as f:
            cf = json.load(f)
        info["n_contrasts"] = len([k for k in cf if not k.startswith("_")])

    ckpt_path = layer_dir / "sae_checkpoints" / "sae_final.pt"
    if ckpt_path.is_file():
        checkpoint = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
        config = checkpoint.get("config", {})
        info["config"] = config
        state = checkpoint.get("model_state_dict", {})
        num_params = sum(v.numel() for v in state.values()) if state else 0
        info["num_params_str"] = f"{num_params:,}" if num_params else "unknown"

    return info


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Upload trained SAEs for all layers to a single Hugging Face repo.",
    )
    p.add_argument(
        "repo_id",
        type=str,
        help="Hugging Face model repo ID (e.g. myorg/kiji-inspector-model).",
    )
    p.add_argument(
        "--output-dir",
        type=str,
        default="/ephemeral/output",
        help="Root output directory containing layer_* subdirectories (default: /ephemeral/output).",
    )
    p.add_argument(
        "--revision",
        type=str,
        default=None,
        help="Branch/revision to push to (default: main).",
    )
    p.add_argument(
        "--commit-message",
        type=str,
        default="Upload SAE checkpoints and feature descriptions",
        help="Commit message for the push.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)

    if not output_dir.is_dir():
        print(f"ERROR: output directory not found: {output_dir}")
        sys.exit(1)

    # Discover layer directories
    layer_dirs = sorted(output_dir.glob("layer_*"))
    if not layer_dirs:
        print(f"ERROR: no layer_* directories found under {output_dir}")
        sys.exit(1)

    layer_names = [d.name for d in layer_dirs]
    print(f"Found {len(layer_dirs)} layers: {', '.join(layer_names)}")

    # Summarise each layer for the model card
    layer_summaries = {}
    for layer_dir in layer_dirs:
        print(f"  Summarising {layer_dir.name}...")
        layer_summaries[layer_dir.name] = _summarise_layer(layer_dir)

    api = HfApi()

    print(f"\nCreating/verifying repo {args.repo_id}...")
    api.create_repo(
        repo_id=args.repo_id,
        repo_type="model",
        private=True,
        exist_ok=True,
    )

    # Upload the entire output directory in one commit using upload_folder.
    # We include layer_* and pairs/ directories.
    print(f"\nUploading {output_dir} to https://huggingface.co/{args.repo_id}...")
    api.upload_folder(
        folder_path=str(output_dir),
        repo_id=args.repo_id,
        repo_type="model",
        revision=args.revision,
        commit_message=args.commit_message,
        allow_patterns=["layer_*/**", "pairs/**"],
    )

    # Generate and upload model card
    print("Generating and uploading model card...")
    card = _build_model_card(args.repo_id, layer_names, layer_summaries)
    api.upload_file(
        path_or_fileobj=card.encode(),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="model",
        revision=args.revision,
        commit_message="Update model card",
    )

    print(f"\nDone. Uploaded {len(layer_dirs)} layers to {args.repo_id}:")
    for name in layer_names:
        info = layer_summaries.get(name, {})
        print(
            f"  {name}: {info.get('n_features', '?')} features, {info.get('n_contrasts', '?')} contrasts"
        )
    if (output_dir / "pairs").is_dir():
        print("  pairs/")
    print("  README.md (model card)")


if __name__ == "__main__":
    main()
