#!/usr/bin/env python3
"""Upload a trained SAE checkpoint to a private Hugging Face model repo.

Usage:
    python src/huggingface/upload_sae.py <repo_id> [--checkpoint output/sae_checkpoints/sae_final.pt]

Example:
    python src/huggingface/upload_sae.py myorg/contrastive-sae
    python src/huggingface/upload_sae.py myorg/contrastive-sae --checkpoint output/sae_checkpoints/sae_final.pt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch
from huggingface_hub import HfApi


def _build_model_card(repo_id: str, checkpoint_path: str) -> str:
    """Generate a model card (README.md) from the SAE checkpoint metadata."""
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    config = checkpoint.get("config", {})

    d_model = config.get("d_model", "unknown")
    d_sae = config.get("d_sae", "unknown")
    dtype = config.get("dtype", "unknown")
    bandwidth = config.get("bandwidth", "unknown")

    state = checkpoint.get("model_state_dict", {})
    num_params = sum(v.numel() for v in state.values()) if state else "unknown"
    if isinstance(num_params, int):
        num_params_str = f"{num_params:,}"
    else:
        num_params_str = str(num_params)

    config_table = "\n".join(f"| `{k}` | `{v}` |" for k, v in sorted(config.items()))

    return f"""---
license: apache-2.0
tags:
  - sparse-autoencoder
  - sae
  - mechanistic-interpretability
  - tool-selection
---

# {repo_id.split("/")[-1]}

JumpReLU Sparse Autoencoder (SAE) trained on contrastive activation data for mechanistic interpretability of tool-selection decisions.

## Architecture

```
input x (d_model={d_model})
    |
    +-> W_enc @ (x - b_dec) + b_enc -> JumpReLU(-, theta) -> features (d_sae={d_sae})
    |
    +-> W_dec @ features + b_dec -> reconstruction (d_model={d_model})
```

- **Type**: JumpReLU SAE with learnable per-feature thresholds
- **Parameters**: {num_params_str}
- **dtype**: {dtype}
- **d_model**: {d_model}
- **d_sae**: {d_sae}
- **bandwidth**: {bandwidth}

## Config

| Key | Value |
|-----|-------|
{config_table}

## Usage

```python
from sae_model import JumpReLUSAE

sae = JumpReLUSAE.from_pretrained("sae_final.pt", device="cuda")
features = sae.encode(activations)
reconstruction = sae.decode(features)
```

Generated by [kiji-inspector](https://github.com/dataiku/kiji-inspector).
"""


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Upload a trained SAE checkpoint to a private Hugging Face model repo.",
    )
    p.add_argument(
        "repo_id",
        type=str,
        help="Hugging Face model repo ID (e.g. myorg/contrastive-sae).",
    )
    p.add_argument(
        "--checkpoint",
        type=str,
        default="output/sae_checkpoints/sae_final.pt",
        help="Path to SAE checkpoint file (default: output/sae_checkpoints/sae_final.pt).",
    )
    p.add_argument(
        "--revision",
        type=str,
        default=None,
        help="Branch/revision to push to (default: main).",
    )
    p.add_argument(
        "--commit-message",
        type=str,
        default="Upload SAE checkpoint",
        help="Commit message for the push.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    checkpoint_path = Path(args.checkpoint)
    if not checkpoint_path.is_file():
        print(f"ERROR: checkpoint not found at {checkpoint_path}")
        sys.exit(1)

    api = HfApi()

    print(f"Creating/verifying repo {args.repo_id}...")
    api.create_repo(
        repo_id=args.repo_id,
        repo_type="model",
        private=True,
        exist_ok=True,
    )

    print("Generating model card...")
    card = _build_model_card(args.repo_id, str(checkpoint_path))

    print(f"Uploading {checkpoint_path} to https://huggingface.co/{args.repo_id}...")
    api.upload_file(
        path_or_fileobj=str(checkpoint_path),
        path_in_repo=checkpoint_path.name,
        repo_id=args.repo_id,
        repo_type="model",
        revision=args.revision,
        commit_message=args.commit_message,
    )
    api.upload_file(
        path_or_fileobj=card.encode(),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="model",
        revision=args.revision,
        commit_message="Update model card",
    )
    print("Done.")


if __name__ == "__main__":
    main()
